### ISSUE TITLE
Can't start training

### ISSUE THREAD

**Issue by emukans** [YunqiuXu/SHA-KG#1]
I have an error starting training:
```sh
File "/SHA-KG/models.py", line 323, in forward
    graph_list = graphs[i].nonzero().cpu().numpy().flatten().tolist()
RuntimeError: cuda runtime error (9) : invalid configuration argument at /pytorch/aten/src/THC/THCGeneral.cpp:371
```

Any ideas on how to solve it? Redis and CoreNLP are started, ports are configured and `openie_path` is changed.

I am using the following dependencies:
```sh
python==3.7.9

CUDA==10.1

# python dependencies
torch==1.3.1
torchvision==0.4.2
tensorflow==1.15
gym==0.17.2
jericho==2.4.0
networkx==2.4
redis==3.4.1
sentencepiece==0.1.95
spacy==2.3.5
fuzzywuzzy==0.18.0
```

Thus, I had an issue:
```sh
File "/SHA-KG/models.py", line 322, in forward
    idx = dec_probs.multinomial(1)
RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement
```
But changing:
```sh
idx = dec_probs.multinomial(1)
```
To:
```sh
idx = dec_probs.multinomial(1, replacement=True)
```
Solved the issue.

**Comment by YunqiuXu** [comment]
Hi Eduard,

Thanks for posting this issue. 

Regarding the issue `RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement`
Could you print the shape of dec_probs? I wonder whether this issue is same as https://github.com/pytorch/pytorch/issues/1584. I re-ran the code with no need for specifying replacement, and got the shape of dec_probs like
```
...
dec_probs torch.Size([10])
dec_probs torch.Size([11])
dec_probs torch.Size([9])
dec_probs torch.Size([9])
dec_probs torch.Size([9])
dec_probs torch.Size([9])
dec_probs torch.Size([15])
...
```

Regarding the issue `RuntimeError: cuda runtime error (9) : invalid configuration argument at /pytorch/aten/src/THC/THCGeneral.cpp:371`. I have never encountered this issue, could you switch your cuda version to 9.2 and re-run the code?

**Comment by emukans** [comment]
Hello @YunqiuXu,

Thank you for a quick reply. dec_probs tensor is empty, this is the reason why it's failing. Here is the output:
```sh
ret_decoder_output.shape: torch.Size([32, 699])
decoder_output.shape: torch.Size([32, 699])
decoder_hidden.shape: torch.Size([1, 32, 100])
dec_probs.shape: torch.Size([0])
```

The question is why it's empty? Maybe I misconfigured something?

P.S.
I removed replacement=True for the output.

**Comment by YunqiuXu** [comment]
Strange issue, your output of 
```
ret_decoder_output.shape: torch.Size([32, 699])
decoder_output.shape: torch.Size([32, 699])
decoder_hidden.shape: torch.Size([1, 32, 100])
```
are as expected.

Here are some other printing outputs:
```
...
ret_decoder_output[i] torch.Size([699])
graphs[i] torch.Size([699])
ret_decoder_output[i][graphs[i]] torch.Size([16])
dec_probs torch.Size([16])
ret_decoder_output[i] torch.Size([699])
graphs[i] torch.Size([699])
ret_decoder_output[i][graphs[i]] torch.Size([10])
dec_probs torch.Size([10])
ret_decoder_output[i] torch.Size([699])
graphs[i] torch.Size([699])
ret_decoder_output[i][graphs[i]] torch.Size([12])
...
```
Maybe your `graphs[i]` (a boolean tensor) are all False, meaning that no entity is extracted (https://github.com/YunqiuXu/SHA-KG/blob/main/gdqn.py#L117). 

Here are my dependencies:
```
CUDA==9.2
tensorflow==1.14.0
numpy==1.19.2
sentencepiece==0.1.85
spacy==2.2.3
fuzzywuzzy==0.17.0
```

**Comment by emukans** [comment]
Graphs were all False indeed. By making further experiments with your code pointed, that the issue could be in the game preset. I used a default `zork1.z5` changing it to `zork3.z5` hidden the issue (`zork2.z5` also didn't work). What presets did you use?

Also, changing masking from `kg` to `interactive` fixed the issue. The code worked on all presets. Can you elaborate on the masking parameter, please? I didn't find anything related to neither in your paper nor in the original paper, the one you took the source codes: [KG-A2C](https://openreview.net/pdf?id=B1x6w0EtwH).

**Comment by YunqiuXu** [comment]
Hi Eduard, 

Sorry for late response.  We conduct experiment on 20 games (please refer Table 1 for details) and haven't tested SHA-KG on other games.  Regarding hyper-parameters, we follow the default setting of our backbone model KG-A2C to run the code (e.g., we use 'kg' mask). We will update our code to refine those irrelevant to our work, thanks for your suggestions.
